<!-- NEUQUEN -->
<div class="itinerario neuquen hide">
    <table class="table table-hover  dark-font">
        <thead>
            <tr>
                <th>ATO Partida</th>
                <th>ATO Arribo</th>
                <th>Fecha Vuelo</th>
                <th>Dia Semana</th>
                <th>Horario Partida</th>
                <th>Horario Arribo</th>
                <th>Num Vuelo</th>
            </tr>
        </thead>
        <tbody class="table-hover">
            <td rowspan="18">AEP</td>
            <td rowspan="18">NQN</td>
            <tr>
                <td>15-jul</td>
                <td>Lunes</td>
                <td>7:10|
                    16:25</td>
                <td>9:10|
                    18:25</td>
                <td>7670|
                    7672</td>
            </tr>
            <tr>
                <td>16-jul</td>
                <td>Martes</td>
                <td>7:05|
                    16:25</td>
                <td>9:05|
                    18:25</td>
                <td>7670|
                    7674</td>
            </tr>
            <tr>
                <td>17-jul</td>
                <td>Miercoles</td>
                <td>7:05|
                    16:50|
                    19:10</td>
                <td>9:05|
                    18:50|
                    21:10</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>18-jul</td>
                <td>Jueves</td>
                <td>7:10|
                    12:45|
                    16:25</td>
                <td>9:10|
                    14:45|
                    18:25</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>19-jul</td>
                <td>Viernes</td>
                <td>7:10|
                    17:20|
                    20:05</td>
                <td>9:10|
                    19:20|
                    22:05</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>20-jul</td>
                <td>Sábado</td>
                <td>7:00|
                    17:25</td>
                <td>9:00|
                    19:25</td>
                <td>7670|
                    7674</td>
            </tr>
            <tr>
                <td>21-jul</td>
                <td>Domingo</td>
                <td>7:00|
                    17:25|
                    19:40</td>
                <td>9:00|
                    19:25|
                    21:40</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>22-jul</td>
                <td>Lunes</td>
                <td>7:10|
                    16:25</td>
                <td>9:10|
                    18:25</td>
                <td>7670|
                    7672</td>
            </tr>
            <tr>
                <td>23-jul</td>
                <td>Martes</td>
                <td>7:05|
                    16:25</td>
                <td>9:05|
                    18:25</td>
                <td>7670|
                    7674</td>
            </tr>
            <tr>
                <td>24-jul</td>
                <td>Miercoles</td>
                <td>7:05|
                    16:50|
                    19:10</td>
                <td>9:05|
                    18:50|
                    21:10</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>25-jul</td>
                <td>Jueves</td>
                <td>7:10|
                    12:45|
                    16:25</td>
                <td>9:10|
                    14:45|
                    18:25</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>26-jul</td>
                <td>Viernes</td>
                <td>7:10|
                    17:20|
                    20:05</td>
                <td>9:10|
                    19:20|
                    22:05</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>27-jul</td>
                <td>Sábado</td>
                <td>7:00|
                    17:25</td>
                <td>9:00|
                    19:25</td>
                <td>7670|
                    7674</td>
            </tr>
            <tr>
                <td>28-jul</td>
                <td>Domingo</td>
                <td>7:00|
                    17:25|
                    19:40</td>
                <td>9:00|
                    19:25|
                    21:40</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
            <tr>
                <td>29-jul</td>
                <td>Lunes</td>
                <td>7:10|
                    16:25</td>
                <td>9:10|
                    18:25</td>
                <td>7670|
                    7672</td>
            </tr>
            <tr>
                <td>30-jul</td>
                <td>Martes</td>
                <td>7:05|
                    16:25</td>
                <td>9:05|
                    18:25</td>
                <td>7670|
                    7674</td>
            </tr>
            <tr>
                <td>31-jul</td>
                <td>Miercoles</td>
                <td>7:05|
                    16:50|
                    19:10</td>
                <td>9:05|
                    18:50|
                    21:10</td>
                <td>7670|
                    7672|
                    7674</td>
            </tr>
        </tbody>
    </table>
</div>

<!-- segunda tabla -->
<div class="itinerario neuquen hide">
    <table class="table table-hover  dark-font">
        <thead>
            <tr>
                <th>ATO Partida</th>
                <th>ATO Arribo</th>
                <th>Fecha Vuelo</th>
                <th>Dia Semana</th>
                <th>Horario Partida</th>
                <th>Horario Arribo</th>
                <th>Num Vuelo</th>
            </tr>
        </thead>
        <tbody class="table-hover">
            <td rowspan="18">NQN</td>
            <td rowspan="18">AEP</td>
            <tr>
                <td>15-jul</td>
                <td>Lunes</td>
                <td>9:50/
                    19:05</td>
                <td>11:25/
                    20:40</td>
                <td>7671/
                    7673</td>
            </tr>
            <tr>
                <td>16-jul</td>
                <td>Martes</td>
                <td>9:45/
                    19:05</td>
                <td>11:20/
                    20:40</td>
                <td>7671/
                    7675</td>
            </tr>
            <tr>
                <td>17-jul</td>
                <td>Miércoles</td>
                <td>9:45/
                    11:50/
                    21:50</td>
                <td>11:20/
                    13:25/
                    23:25</td>
                <td>7671/
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>18-jul</td>
                <td>Jueves</td>
                <td>9:50/
                    15:25/
                    19:05</td>
                <td>11:25/
                    17:00|
                    20:40</td>
                <td>7671/
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>19-jul</td>
                <td>Viernes</td>
                <td>9:50/
                    11:50/
                    22:45</td>
                <td>11:25/
                    13:25/
                    0:20</td>
                <td>7671/
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>20-jul</td>
                <td>Sábado</td>
                <td>9:40/
                    20:05</td>
                <td>11:15/
                    21:40</td>
                <td>7671/
                    7675</td>
            </tr>
            <tr>
                <td>21-jul</td>
                <td>Domingo</td>
                <td>9:40/
                    11:45/
                    22:20</td>
                <td>11:15/
                    13:20/
                    23:55</td>
                <td>76717
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>22-jul</td>
                <td>Lunes</td>
                <td>9:50/
                    19:05</td>
                <td>11:25/
                    20:40</td>
                <td>7671/
                    7673</td>
            </tr>
            <tr>
                <td>23-jul</td>
                <td>Martes</td>
                <td>9:45/
                    19:05</td>
                <td>11:20/
                    20:40</td>
                <td>7671/
                    7675</td>
            </tr>
            <tr>
                <td>24-jul</td>
                <td>Miércoles</td>
                <td>9:45/
                    11:50/
                    21:50</td>
                <td>11:20/
                    13:25/
                    23:25</td>
                <td>7671/
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>25-jul</td>
                <td>Jueves</td>
                <td>9:50/
                    15:25/
                    19:05</td>
                <td>11:25/
                    17:00|
                    20:40</td>
                <td>7671/
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>26-jul</td>
                <td>Viernes</td>
                <td>9:50/
                    11:50/
                    22:45</td>
                <td>11:25/
                    13:25/
                    0:20</td>
                <td>7671/
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>27-jul</td>
                <td>Sábado</td>
                <td>9:40/
                    20:05</td>
                <td>11:15/
                    21:40</td>
                <td>7671/
                    7675</td>
            </tr>
            <tr>
                <td>28-jul</td>
                <td>Domingo</td>
                <td>9:40/
                    11:45/
                    22:23</td>
                <td>11:15/
                    13:20/
                    23:58</td>
                <td>7671/
                    7673/
                    7675</td>
            </tr>
            <tr>
                <td>29-jul</td>
                <td>Lunes</td>
                <td>9:50/
                    19:05</td>
                <td>11:25/
                    20:40</td>
                <td>7671/
                    7673</td>
            </tr>
            <tr>
                <td>30-jul</td>
                <td>Martes</td>
                <td>9:45/
                    19:05</td>
                <td>11:20/
                    20:40</td>
                <td>7671/
                    7675</td>
            </tr>
            <tr>
                <td>31-jul</td>
                <td>Martes</td>
                <td>9:45/
                    11:50</td>
                <td>11:20/
                    13:25</td>
                <td>7671/
                    7673</td>
            </tr>
        </tbody>
    </table>
</div>
<!-- /NEUQUEN -->