<!-- TUCUMAN -->
<div class="itinerario tucuman hide">
    <table class="table table-hover  dark-font">
        <thead>
            <tr>
                <th>ATO Partida</th>
                <th>ATO Arribo</th>
                <th>Fecha Vuelo</th>
                <th>Dia Semana</th>
                <th>Horario Partida</th>
                <th>Horario Arribo</th>
                <th>Num Vuelo</th>
            </tr>
        </thead>
        <tbody class="table-hover">
            <td rowspan="18">AEP</td>
            <td rowspan="18">TUC</td>
            <tr>
                <td>15-jul.-19</td>
                <td>Lunes</td>
                <td>6:15/
                    12:46/
                    18:51</td>
                <td>8:15/
                    14:46/
                    20:51</td>
                <td>7570/
                    7574/
                    7576</td>
            </tr>
            <tr>
                <td>16-jul.-19</td>
                <td>Martes</td>
                <td>6:15/
                    15:00/
                    19:05</td>
                <td>8:15/
                    17:00/
                    21:05</td>
                <td>7570/
                    7572/
                    7576</td>
            </tr>
            <tr>
                <td>17-jul.-19</td>
                <td>Miercoles</td>
                <td>6:10/
                    13:50/
                    18:40</td>
                <td>8:10/
                    15:50/
                    20:40</td>
                <td>7570/
                    7572/
                    7574</td>
            </tr>
            <tr>
                <td>18-jul.-19</td>
                <td>Jueves</td>
                <td>6:10/
                    13:40/
                    18:50</td>
                <td>8:10/
                    15:40/
                    20:50</td>
                <td>7570/
                    7572/
                    7576</td>
            </tr>
            <tr>
                <td>19-jul.-19</td>
                <td>Viernes</td>
                <td>6:10/
                    12:43/
                    18:55</td>
                <td>8:10/
                    14:43/
                    20:55</td>
                <td>7570/
                    7572/
                    7576</td>
            </tr>
            <tr>
                <td>20-jul.-19</td>
                <td>Sábado</td>
                <td>6:35/
                    17:55</td>
                <td>8:35/
                    19:55</td>
                <td>7570/
                    7576</td>
            </tr>
            <tr>
                <td>21-jul.-19</td>
                <td>Domingo</td>
                <td>12:05/
                    17:50/
                    19:30</td>
                <td>14:05/
                    19:47/
                    21:27</td>
                <td>7570/
                    7574/
                    7576</td>
            </tr>
            <tr>
                <td>22-jul.-19</td>
                <td>Lunes</td>
                <td>6:15/
                    12:46/
                    18:51</td>
                <td>8:15/
                    14:46/
                    20:51</td>
                <td>7570/
                    7574/
                    7576</td>
            </tr>
            <tr>
                <td>23-jul.-19</td>
                <td>Martes</td>
                <td>6:15/
                    15:00/
                    19:05</td>
                <td>8:15/
                    17:00/
                    21:05</td>
                <td>7570/
                    7572/
                    7576</td>
            </tr>
            <tr>
                <td>24-jul.-19</td>
                <td>Miercoles</td>
                <td>6:10/
                    13:50/
                    18:40</td>
                <td>8:10/
                    15:50/
                    20:40</td>
                <td>7570/
                    7572/
                    7574</td>
            </tr>
            <tr>
                <td>25-jul.-19</td>
                <td>Jueves</td>
                <td>6:10/
                    13:40/
                    18:50</td>
                <td>8:10/
                    15:40/
                    20:50</td>
                <td>7570/
                    7572/
                    7576</td>
            </tr>
            <tr>
                <td>26-jul.-19</td>
                <td>Viernes</td>
                <td>6:10/
                    12:42/
                    18:55</td>
                <td>8:10/
                    14:42/
                    20:55</td>
                <td>7570/
                    7572/
                    7576</td>
            </tr>
            <tr>
                <td>27-jul.-19</td>
                <td>Sábado</td>
                <td>6:35/
                    17:55</td>
                <td>8:35/
                    19:55</td>
                <td>7570/
                    7576</td>
            </tr>
            <tr>
                <td>28-jul.-19</td>
                <td>Domingo</td>
                <td>12:05/
                    17:50/
                    19:30</td>
                <td>14:05/
                    19:47/
                    21:27</td>
                <td>7570/
                    7574/
                    7576</td>
            </tr>
            <tr>
                <td>29-jul.-19</td>
                <td>Lunes</td>
                <td>6:15/
                    12:46/
                    18:51</td>
                <td>8:15/
                    14:46/
                    20:51</td>
                <td>7570/
                    7574/
                    7576</td>
            </tr>
            <tr>
                <td>30-jul.-19</td>
                <td>Martes</td>
                <td>6:15/
                    15:00/
                    19:05</td>
                <td>8:15/
                    17:00/
                    21:05</td>
                <td>7570/
                    7572/
                    7576</td>
            </tr>
            <tr>
                <td>31-jul.-19</td>
                <td>Miercoles</td>
                <td>6:10/
                    13:50/
                    18:40</td>
                <td>8:10/
                    15:50/
                    20:40</td>
                <td>7570/
                    7572/
                    7574</td>
            </tr>
        </tbody>
    </table>
</div>

<div class="itinerario tucuman hide">
    <table class="table table-hover  dark-font">
        <thead>
            <tr>
                <th>ATO Partida</th>
                <th>ATO Arribo</th>
                <th>Fecha Vuelo</th>
                <th>Dia Semana</th>
                <th>Horario Partida</th>
                <th>Horario Arribo</th>
                <th>Num Vuelo</th>
            </tr>
        </thead>
        <tbody class="table-hover">
            <td rowspan="18">TUC</td>
            <td rowspan="18">AEP</td>
            <tr>
                <td>15-jul.-19</td>
                <td>Lunes</td>
                <td>9:00/
                    15:25/
                    21:30</td>
                <td>10:44/
                    17:06/
                    23:14</td>
                <td>7571/
                    7575/
                    7577</td>
            </tr>
            <tr>
                <td>16-jul.-19</td>
                <td>Martes</td>
                <td>9:00/
                    14:35/
                    21:45</td>
                <td>10:44/
                    16:19/
                    23:29</td>
                <td>7571/
                    7573/
                    7577</td>
            </tr>
            <tr>
                <td>17-jul.-19</td>
                <td>Miércoles</td>
                <td>8:48/
                    16:30/
                    21:20</td>
                <td>10:32/
                    18:14/
                    23:04</td>
                <td>7571/
                    7573/
                    7575</td>
            </tr>
            <tr>
                <td>18-jul.-19</td>
                <td>Jueves</td>
                <td>8:50/
                    16:20/
                    21:30</td>
                <td>10:31/
                    18:04/
                    23:14</td>
                <td>7571/
                    7573/
                    7577</td>
            </tr>
            <tr>
                <td>19-jul.-19</td>
                <td>Viernes</td>
                <td>8:50/
                    15:21/
                    21:35</td>
                <td>10:31/
                    17:05/
                    23:19</td>
                <td>7571/
                    7573/
                    7577</td>
            </tr>
            <tr>
                <td>20-jul.-19</td>
                <td>Sábado</td>
                <td>12:40/
                    20:35</td>
                <td>14:24/
                    22:19</td>
                <td>7571/
                    7577</td>
            </tr>
            <tr>
                <td>21-jul.-19</td>
                <td>Domingo</td>
                <td>14:45/
                    20:30/
                    22:05</td>
                <td>16:29/
                    22:11/
                    23:46</td>
                <td>7571/
                    7575/
                    7577</td>
            </tr>
            <tr>
                <td>22-jul.-19</td>
                <td>Lunes</td>
                <td>9:00/
                    15:25/
                    21:30</td>
                <td>10:44/
                    17:06/
                    23:14</td>
                <td>7571/
                    7575/
                    7577</td>
            </tr>
            <tr>
                <td>23-jul.-19</td>
                <td>Martes</td>
                <td>9:00/
                    14:35/
                    21:45</td>
                <td>10:44/
                    16:19/
                    23:29</td>
                <td>7571/
                    7573/
                    7577</td>
            </tr>
            <tr>
                <td>24-jul.-19</td>
                <td>Miércoles</td>
                <td>8:48/
                    16:30/
                    21:20</td>
                <td>10:32/
                    18:14/
                    23:04</td>
                <td>7571/
                    7573/
                    7575</td>
            </tr>
            <tr>
                <td>25-jul.-19</td>
                <td>Jueves</td>
                <td>8:50/
                    16:20/
                    21:30</td>
                <td>10:31/
                    18:04/
                    23:14</td>
                <td>7571/
                    7573/
                    7577</td>
            </tr>
            <tr>
                <td>26-jul.-19</td>
                <td>Viernes</td>
                <td>8:50/
                    15:20/
                    21:35</td>
                <td>10:34/
                    17:04/
                    23:19</td>
                <td>7571/
                    7573/
                    7577</td>
            </tr>
            <tr>
                <td>27-jul.-19</td>
                <td>Sábado</td>
                <td>12:40/
                    20:35</td>
                <td>14:24/
                    22:19</td>
                <td>7571/
                    7577</td>
            </tr>
            <tr>
                <td>28-jul.-19</td>
                <td>Domingo</td>
                <td>14:45/
                    20:30/
                    22:05</td>
                <td>16:29/
                    22:11/
                    23:46</td>
                <td>7571/
                    7575/
                    7577</td>
            </tr>
            <tr>
                <td>29-jul.-19</td>
                <td>Lunes</td>
                <td>9:00/
                    15:25/
                    21:30</td>
                <td>10:44/
                    17:06/
                    23:14</td>
                <td>7571/
                    7575/
                    7577</td>
            </tr>
            <tr>
                <td>30-jul.-19</td>
                <td>Martes</td>
                <td>9:00/
                    14:35/
                    21:45</td>
                <td>10:44/
                    16:19/
                    23:29</td>
                <td>7571/
                    7573/
                    7577</td>
            </tr>
            <tr>
                <td>31-jul.-19</td>
                <td>Martes</td>
                <td>8:48/
                    16:30</td>
                <td>10:32/
                    18:14</td>
                <td>7571/
                    7573</td>
            </tr>
        </tbody>
    </table>
</div>
<!-- /NEUQUEN -->